development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p9eb1748dbcfded7a288c1c980ba01ca9a915b304c21e99ceab9f5cbb0119b938@ec2-34-225-146-66.compute-1.amazonaws.com:36389
